site_name: lernOS Zettelkasten learning path
site_url: https://github.com/cogneon/lernos-zettelkasten/
docs_dir: src
site_dir: ../docs/en


nav:
    - Welcome: index.md
    - About Lern OS:
      - Live Long Learning: 1-1-Lebenslanges-Lernen-und-Wissensarbeit.md
      - Canvas: 1-2-lernOS-Canvas.md
      - Flow: 1-3-lernOS-Flow.md
      - Workplace: 1-4-lernOS-Workplace.md
      - Memex: 1-5-lernOS-Memex.md
    - Basics:
      - PKM Basics: 2-0-PKM-Grundlagen.md
    - Learning Pathway:
      - Learning Pathway Overview: 2-0-Lernpfad-Ueberblick.md
      - Week 0 (Sprint Setup): 2-1-Woche-0.md
      - Week 1 (Goal definition): 2-1-Woche-1.md
      - Week 2 (Getting to know notes): 2-1-Woche-2.md
      - Week 3 (Create your first notes): 2-1-Woche-3.md
      - Week 4 (Find your workflow): 2-1-Woche-4.md
      - Week 5 (Create permanent notes): 2-1-Woche-5.md
      - Week 6 (Frittering): 2-1-Woche-6.md
      - Week 7 (Pit stop): 2-1-Woche-7.md
      - Week 8 (Retrievability of knowledge): 2-1-Woche-8.md
      - Week 9 (Thinking in the Zettelkasten): 2-1-Woche-9.md
      - Week 10 (Deepening the workflow): 2-1-Woche-10.md
      - Week 11 (Reflection and conclusion): 2-1-Woche-11.md
    - Kata-Log:
      - Kata 0 (Circle Setup): 2-1-Kata-0.md
      - Kata 1 (My goal for the next 12 weeks): 2-1-Kata-1.md
      - Kata 2 (An appointment with yourself): 2-1-Kata-2.md
      - Kata 3 (Set up PKM environment): 2-1-Kata-3.md
      - Kata 4 (Give feedback): 2-1-Kata-4.md
      - Kata 5 (Get to know notes): 2-1-Kata-5.md
      - Kata 6 (Progressive Summarization): 2-1-Kata-6.md
      - Kata 7 (Create first notes): 2-1-Kata-7.md
      - Kata 8 (Create permanent notes): 2-1-Kata-8.md
      - Kata 9 (Frittering): 2-1-Kata-9.md
      - Kata 10 (are you on track?): 2-1-Kata-10.md
      - Kata 11 (Outlook): 2-1-Kata-11.md
      - Kata 12 (Retrievability of knowledge): 2-1-Kata-12.md
      - Kata 13 (Map Of Content in 3 Steps): 2-1-Kata-13.md
      - Kata 14 (Thinking in the Zettelkasten): 2-1-Kata-14.md
      - Kata 15 (Find your workflow): 2-1-Kata-15.md
      - Kata 16 (Retrospective): 2-1-Kata-16.md
      - Kata 17 (Deepen your workflow): 2-1-Kata-17.md
    - Appendix:
      - Getting started with Markdown: 3-0-1-was-ist-markdown.md
      - Change from proprietary format: 3-0-2-proprietaeres-Format-zu-MD.md
      - Guide um PKM mit OneNote umzusetzen: 3-0-3-Guide-PKM-mit-OneNote.md
      - Acknowledgement: 3-0-0-Danksagung.md
      - Change history: 3-0-99-Aenderungshistorie.md

    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-zettelkasten/blob/main/en/lernOS-Zettelkasten-Guide-en.pdf
      - Word-Version: https://github.com/cogneon/lernos-zettelkasten/blob/main/en/lernOS-Zettelkasten-Guide-en.docx
      - HTML-Version: https://github.com/cogneon/lernos-zettelkasten/blob/main/en/lernOS-Zettelkasten-Guide-en.html
      - E-Book (epub): https://github.com/cogneon/lernos-zettelkasten/blob/main/en/lernOS-Zettelkasten-Guide-en.epub
      - E-Book (mobi): https://github.com/cogneon/lernos-zettelkasten/blob/main/en/lernOS-Zettelkasten-Guide-en.mobi
      - Vault: https://github.com/cogneon/lernos-zettelkasten/blob/main/en/LernOS-Zettelkasten.zip
    - Links:
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos-zettelkasten'
repo_url: 'https://github.com/cogneon/lernos-zettelkasten/'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/lern_os'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    analytics:
       provider: custom
    alternate:
     - name: Deutsch
       link: https://cogneon.github.io/lernos-zettelkasten/de
       lang: de

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search
  - mermaid2
