site_name: lernOS Zettelkasten learning path
site_url: https://github.com/cogneon/lernos-zettelkasten/
docs_dir: src
site_dir: ../docs/en


nav:
    - Welcome: index.md
    - About Lern OS:
      - Live Long Learning: 1-1-Lebenslanges-Lernen-und-Wissensarbeit.md
      - Canvas: 1-2-lernOS-Canvas.md
      - Flow: 1-3-lernOS-Flow.md
      - Workplace: 1-4-lernOS-Workplace.md
      - Memex: 1-5-lernOS-Memex.md
    - Basics:
      - PKM Basics: 2-0-PKM-Grundlagen.md
    - Learning Pathway:
      - Learning Pathway Overview: 2-0-Lernpfad-Ueberblick.md
      - Week 0: 2-1-Kata-0.md
      - Week 1: 2-1-Kata-1.md
      - Week 2: 2-1-Kata-2.md
      - Week 3: 2-1-Kata-3.md
      - Week 4: 2-1-Kata-4.md
      - Week 5: 2-1-Kata-5.md
      - Week 6: 2-1-Kata-6.md
      - Week 7: 2-1-Kata-7.md
      - Week 8: 2-1-Kata-8.md
      - Week 9: 2-1-Kata-9.md
      - Week 10: 2-1-Kata-10.md
      - Week 11: 2-1-Kata-11.md
      - Week 12: 2-1-Kata-12.md
    - Appendix:
      - Getting started with Markdown: 3-0-1-was-ist-markdown.md
      - Change from proprietary format: 3-0-2-proprietaeres-Format-zu-MD.md
      - Guide um PKM mit OneNote umzusetzen: 3-0-3-Guide-PKM-mit-OneNote.md
      - Acknowledgement: 3-0-0-Danksagung.md
      - Change history: 3-0-99-Aenderungshistorie.md

    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-zettelkasten/blob/master/en/lernOS-Zettelkasten-Guide-en.pdf
      - Word-Version: https://github.com/cogneon/lernos-zettelkasten/blob/master/en/lernOS-Zettelkasten-Guide-en.docx
      - HTML-Version: https://github.com/cogneon/lernos-zettelkasten/blob/master/en/lernOS-Zettelkasten-Guide-en.html
      - E-Book (epub): https://github.com/cogneon/lernos-zettelkasten/blob/master/en/lernOS-Zettelkasten-Guide-en.epub
      - E-Book (mobi): https://github.com/cogneon/lernos-zettelkasten/blob/master/en/lernOS-Zettelkasten-Guide-en.mobi
    - Links:
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos-zettelkasten'
repo_url: 'https://github.com/cogneon/lernos-zettelkasten/'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/lern_os'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    analytics:
       provider: custom
    alternate:
     - name: Deutsch
       link: https://cogneon.github.io/lernos-zettelkasten/de
       lang: de

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search
  - mermaid2
